version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/src/app"
    depends_on:
      - redis
      - mysql
  redis:
    image: redis
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: secretsquirrel
    image: mysql:5.5.48
